# Site settings
title: 小生奋斗史 
email: shxz130@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    I'm a coder, and I'm on the road ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: shxz130
github_username:  shxz130

# Build settings
markdown: kramdown
