markdown: redcarpet
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: page/:num
encoding: "utf-8"
future: true
lsi: false
safe: true

redcarpet:
    extensions:
        - with_toc_data
        - hard_wrap
        - no_intra_emphasis
        - tables
        - fenced_code_blocks
        - autolink

blog:
    name: Silly boy# 博客名称
    description: 一个小傻子的奋斗史 # 博客描述
    title: 一个小傻子的奋斗史 # 网页标题
    url: shxz130.github.io # 博客地址
    duoshuo:  # 多说ID
    tongji:  # 百度统计ID
    qiniu: # 七牛云地址
author:
    name: 张博 # 作者名称
    email: shxz130@gmail.com # 邮箱地址
    weibo: http://weibo.com/u/2924623323 # 微博地址
    github: https://github.com/shxz130 # GitHub地址
    logo: /res/img/shxz130.jpg # logo地址
    douban:
        name:    # 豆瓣地址名称
        key:     # 豆瓣API Key
